services:
  postgres:
    image: postgres:17.0
    container_name: postgres-isolation-levels
    restart: unless-stopped
    ports:
      - 3500:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
